modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="schedulemc"
version="1.0.0"
displayName="ScheduleMC"
description="ScheduleMC Main Mod"

# Dependencies (falls n√∂tig)
[[dependencies.schedulemc]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
